/**
 * Swiss Corporate API
 * This is the release candidate version of the \"Swiss Corporate API\" specification. 
 *
 * OpenAPI spec version: 1.0.0.2-SNAPSHOT
 * Contact: swisscorpapi@six-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwissCorporateApi);
  }
}(this, function(expect, SwissCorporateApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwissCorporateApi.Iso20022Api();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Iso20022Api', function() {
    describe('retrieveIso20022AccountStatement', function() {
      it('should call retrieveIso20022AccountStatement successfully', function(done) {
        //uncomment below and update the code to test retrieveIso20022AccountStatement
        //instance.retrieveIso20022AccountStatement(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveIso20022AccountStatementIds', function() {
      it('should call retrieveIso20022AccountStatementIds successfully', function(done) {
        //uncomment below and update the code to test retrieveIso20022AccountStatementIds
        //instance.retrieveIso20022AccountStatementIds(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveIso20022PaymentInstruction', function() {
      it('should call retrieveIso20022PaymentInstruction successfully', function(done) {
        //uncomment below and update the code to test retrieveIso20022PaymentInstruction
        //instance.retrieveIso20022PaymentInstruction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveIso20022PaymentInstructionStatusReport', function() {
      it('should call retrieveIso20022PaymentInstructionStatusReport successfully', function(done) {
        //uncomment below and update the code to test retrieveIso20022PaymentInstructionStatusReport
        //instance.retrieveIso20022PaymentInstructionStatusReport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('submitIso20022PaymentInstruction', function() {
      it('should call submitIso20022PaymentInstruction successfully', function(done) {
        //uncomment below and update the code to test submitIso20022PaymentInstruction
        //instance.submitIso20022PaymentInstruction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
