/**
 * Swiss Corporate API
 * This is the release candidate version of the \"Swiss Corporate API\" specification. 
 *
 * OpenAPI spec version: 1.0.0.2-SNAPSHOT
 * Contact: swisscorpapi@six-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccountTransactionItemChargesRecord'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AccountTransactionItemChargesRecord'));
  } else {
    // Browser globals (root is window)
    if (!root.SwissCorporateApi) {
      root.SwissCorporateApi = {};
    }
    root.SwissCorporateApi.AccountTransactionItemCharges = factory(root.SwissCorporateApi.ApiClient, root.SwissCorporateApi.AccountTransactionItemChargesRecord);
  }
}(this, function(ApiClient, AccountTransactionItemChargesRecord) {
  'use strict';




  /**
   * The AccountTransactionItemCharges model module.
   * @module model/AccountTransactionItemCharges
   * @version 1.0.0.2-SNAPSHOT
   */

  /**
   * Constructs a new <code>AccountTransactionItemCharges</code>.
   * @alias module:model/AccountTransactionItemCharges
   * @class
   * @param amount {String} 
   * @param currency {String} 
   */
  var exports = function(amount, currency) {
    var _this = this;

    _this['amount'] = amount;
    _this['currency'] = currency;

  };

  /**
   * Constructs a <code>AccountTransactionItemCharges</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccountTransactionItemCharges} obj Optional instance to populate.
   * @return {module:model/AccountTransactionItemCharges} The populated <code>AccountTransactionItemCharges</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
      }
      if (data.hasOwnProperty('currency')) {
        obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
      }
      if (data.hasOwnProperty('chargeRecords')) {
        obj['chargeRecords'] = ApiClient.convertToType(data['chargeRecords'], [AccountTransactionItemChargesRecord]);
      }
    }
    return obj;
  }

  /**
   * @member {String} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * @member {String} currency
   */
  exports.prototype['currency'] = undefined;
  /**
   * @member {Array.<module:model/AccountTransactionItemChargesRecord>} chargeRecords
   */
  exports.prototype['chargeRecords'] = undefined;



  return exports;
}));


