/**
 * Swiss Corporate API
 * This is the release candidate version of the \"Swiss Corporate API\" specification. 
 *
 * OpenAPI spec version: 1.0.0.2-SNAPSHOT
 * Contact: swisscorpapi@six-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwissCorporateApi) {
      root.SwissCorporateApi = {};
    }
    root.SwissCorporateApi.CommonStructuredAddress = factory(root.SwissCorporateApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CommonStructuredAddress model module.
   * @module model/CommonStructuredAddress
   * @version 1.0.0.2-SNAPSHOT
   */

  /**
   * Constructs a new <code>CommonStructuredAddress</code>.
   * @alias module:model/CommonStructuredAddress
   * @class
   * @param streetName {String} 
   * @param postCode {String} 
   * @param townName {String} 
   * @param country {String} 
   */
  var exports = function(streetName, postCode, townName, country) {
    var _this = this;

    _this['streetName'] = streetName;

    _this['postCode'] = postCode;
    _this['townName'] = townName;
    _this['country'] = country;
  };

  /**
   * Constructs a <code>CommonStructuredAddress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CommonStructuredAddress} obj Optional instance to populate.
   * @return {module:model/CommonStructuredAddress} The populated <code>CommonStructuredAddress</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('streetName')) {
        obj['streetName'] = ApiClient.convertToType(data['streetName'], 'String');
      }
      if (data.hasOwnProperty('buildingNumber')) {
        obj['buildingNumber'] = ApiClient.convertToType(data['buildingNumber'], 'String');
      }
      if (data.hasOwnProperty('postCode')) {
        obj['postCode'] = ApiClient.convertToType(data['postCode'], 'String');
      }
      if (data.hasOwnProperty('townName')) {
        obj['townName'] = ApiClient.convertToType(data['townName'], 'String');
      }
      if (data.hasOwnProperty('country')) {
        obj['country'] = ApiClient.convertToType(data['country'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} streetName
   */
  exports.prototype['streetName'] = undefined;
  /**
   * @member {String} buildingNumber
   */
  exports.prototype['buildingNumber'] = undefined;
  /**
   * @member {String} postCode
   */
  exports.prototype['postCode'] = undefined;
  /**
   * @member {String} townName
   */
  exports.prototype['townName'] = undefined;
  /**
   * @member {String} country
   */
  exports.prototype['country'] = undefined;



  return exports;
}));


