/**
 * Swiss Corporate API
 * This is the release candidate version of the \"Swiss Corporate API\" specification. 
 *
 * OpenAPI spec version: 1.0.0.2-SNAPSHOT
 * Contact: swisscorpapi@six-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwissCorporateApi) {
      root.SwissCorporateApi = {};
    }
    root.SwissCorporateApi.CommonErrorType = factory(root.SwissCorporateApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class CommonErrorType.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "/problems/INVALID_PAYLOAD"
     * @const
     */
    "INVALID_PAYLOAD": "/problems/INVALID_PAYLOAD",
    /**
     * value: "/problems/MALFORMED_PAYLOAD"
     * @const
     */
    "MALFORMED_PAYLOAD": "/problems/MALFORMED_PAYLOAD",
    /**
     * value: "/problems/INVALID_TOKEN"
     * @const
     */
    "INVALID_TOKEN": "/problems/INVALID_TOKEN",
    /**
     * value: "/problems/EXPIRED_TOKEN"
     * @const
     */
    "EXPIRED_TOKEN": "/problems/EXPIRED_TOKEN",
    /**
     * value: "/problems/INSUFFICIENT_PRIVILEGES"
     * @const
     */
    "INSUFFICIENT_PRIVILEGES": "/problems/INSUFFICIENT_PRIVILEGES",
    /**
     * value: "/problems/NO_ACCESS_TO_RESOURCE"
     * @const
     */
    "NO_ACCESS_TO_RESOURCE": "/problems/NO_ACCESS_TO_RESOURCE",
    /**
     * value: "/problems/RESOURCE_DOES_NOT_EXIST"
     * @const
     */
    "RESOURCE_DOES_NOT_EXIST": "/problems/RESOURCE_DOES_NOT_EXIST",
    /**
     * value: "/problems/RESOURCE_NOT_READY"
     * @const
     */
    "RESOURCE_NOT_READY": "/problems/RESOURCE_NOT_READY",
    /**
     * value: "/problems/RESOURCE_TOO_LARGE"
     * @const
     */
    "RESOURCE_TOO_LARGE": "/problems/RESOURCE_TOO_LARGE",
    /**
     * value: "/problems/WRONG_METHOD"
     * @const
     */
    "WRONG_METHOD": "/problems/WRONG_METHOD",
    /**
     * value: "/problems/OPERATION_NOT_ALLOWED"
     * @const
     */
    "OPERATION_NOT_ALLOWED": "/problems/OPERATION_NOT_ALLOWED",
    /**
     * value: "/problems/TECHNICAL_ERROR"
     * @const
     */
    "TECHNICAL_ERROR": "/problems/TECHNICAL_ERROR"  };

  /**
   * Returns a <code>CommonErrorType</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/CommonErrorType} The enum <code>CommonErrorType</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


