/**
 * Swiss Corporate API
 * This is the release candidate version of the \"Swiss Corporate API\" specification. 
 *
 * OpenAPI spec version: 1.0.0.2-SNAPSHOT
 * Contact: swisscorpapi@six-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwissCorporateApi) {
      root.SwissCorporateApi = {};
    }
    root.SwissCorporateApi.CommonClearingSystemMemberIdentification = factory(root.SwissCorporateApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CommonClearingSystemMemberIdentification model module.
   * @module model/CommonClearingSystemMemberIdentification
   * @version 1.0.0.2-SNAPSHOT
   */

  /**
   * Constructs a new <code>CommonClearingSystemMemberIdentification</code>.
   * @alias module:model/CommonClearingSystemMemberIdentification
   * @class
   * @param code {String} 
   * @param memberId {String} 
   */
  var exports = function(code, memberId) {
    var _this = this;

    _this['code'] = code;
    _this['memberId'] = memberId;
  };

  /**
   * Constructs a <code>CommonClearingSystemMemberIdentification</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CommonClearingSystemMemberIdentification} obj Optional instance to populate.
   * @return {module:model/CommonClearingSystemMemberIdentification} The populated <code>CommonClearingSystemMemberIdentification</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'String');
      }
      if (data.hasOwnProperty('memberId')) {
        obj['memberId'] = ApiClient.convertToType(data['memberId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} code
   */
  exports.prototype['code'] = undefined;
  /**
   * @member {String} memberId
   */
  exports.prototype['memberId'] = undefined;



  return exports;
}));


