/**
 * Swiss Corporate API
 * This is the release candidate version of the \"Swiss Corporate API\" specification. 
 *
 * OpenAPI spec version: 1.0.0.2-SNAPSHOT
 * Contact: swisscorpapi@six-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwissCorporateApi) {
      root.SwissCorporateApi = {};
    }
    root.SwissCorporateApi.ConsentAccountItem = factory(root.SwissCorporateApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ConsentAccountItem model module.
   * @module model/ConsentAccountItem
   * @version 1.0.0.2-SNAPSHOT
   */

  /**
   * Constructs a new <code>ConsentAccountItem</code>.
   * @alias module:model/ConsentAccountItem
   * @class
   * @param accountId {String} 
   * @param iban {String} 
   */
  var exports = function(accountId, iban) {
    var _this = this;

    _this['accountId'] = accountId;
    _this['iban'] = iban;



  };

  /**
   * Constructs a <code>ConsentAccountItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConsentAccountItem} obj Optional instance to populate.
   * @return {module:model/ConsentAccountItem} The populated <code>ConsentAccountItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accountId')) {
        obj['accountId'] = ApiClient.convertToType(data['accountId'], 'String');
      }
      if (data.hasOwnProperty('iban')) {
        obj['iban'] = ApiClient.convertToType(data['iban'], 'String');
      }
      if (data.hasOwnProperty('currency')) {
        obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
      }
      if (data.hasOwnProperty('designation')) {
        obj['designation'] = ApiClient.convertToType(data['designation'], 'String');
      }
      if (data.hasOwnProperty('allowedCurrencies')) {
        obj['allowedCurrencies'] = ApiClient.convertToType(data['allowedCurrencies'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {String} accountId
   */
  exports.prototype['accountId'] = undefined;
  /**
   * @member {String} iban
   */
  exports.prototype['iban'] = undefined;
  /**
   * @member {String} currency
   */
  exports.prototype['currency'] = undefined;
  /**
   * @member {String} designation
   */
  exports.prototype['designation'] = undefined;
  /**
   * @member {Array.<String>} allowedCurrencies
   */
  exports.prototype['allowedCurrencies'] = undefined;



  return exports;
}));


