/**
 * Swiss Corporate API
 * This is the release candidate version of the \"Swiss Corporate API\" specification. 
 *
 * OpenAPI spec version: 1.0.0.2-SNAPSHOT
 * Contact: swisscorpapi@six-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ConsentAccountItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ConsentAccountItem'));
  } else {
    // Browser globals (root is window)
    if (!root.SwissCorporateApi) {
      root.SwissCorporateApi = {};
    }
    root.SwissCorporateApi.ConsentItem = factory(root.SwissCorporateApi.ApiClient, root.SwissCorporateApi.ConsentAccountItem);
  }
}(this, function(ApiClient, ConsentAccountItem) {
  'use strict';




  /**
   * The ConsentItem model module.
   * @module model/ConsentItem
   * @version 1.0.0.2-SNAPSHOT
   */

  /**
   * Constructs a new <code>ConsentItem</code>.
   * @alias module:model/ConsentItem
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ConsentItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConsentItem} obj Optional instance to populate.
   * @return {module:model/ConsentItem} The populated <code>ConsentItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('useCase')) {
        obj['useCase'] = ApiClient.convertToType(data['useCase'], 'String');
      }
      if (data.hasOwnProperty('accounts')) {
        obj['accounts'] = ApiClient.convertToType(data['accounts'], [ConsentAccountItem]);
      }
    }
    return obj;
  }

  /**
   * @member {String} useCase
   */
  exports.prototype['useCase'] = undefined;
  /**
   * @member {Array.<module:model/ConsentAccountItem>} accounts
   */
  exports.prototype['accounts'] = undefined;



  return exports;
}));


