/**
 * Swiss Corporate API
 * This is the release candidate version of the \"Swiss Corporate API\" specification. 
 *
 * OpenAPI spec version: 1.0.0.2-SNAPSHOT
 * Contact: swisscorpapi@six-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DirectoryImageReference'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DirectoryImageReference'));
  } else {
    // Browser globals (root is window)
    if (!root.SwissCorporateApi) {
      root.SwissCorporateApi = {};
    }
    root.SwissCorporateApi.DirectoryMultisizeImageReference = factory(root.SwissCorporateApi.ApiClient, root.SwissCorporateApi.DirectoryImageReference);
  }
}(this, function(ApiClient, DirectoryImageReference) {
  'use strict';




  /**
   * The DirectoryMultisizeImageReference model module.
   * @module model/DirectoryMultisizeImageReference
   * @version 1.0.0.2-SNAPSHOT
   */

  /**
   * Constructs a new <code>DirectoryMultisizeImageReference</code>.
   * @alias module:model/DirectoryMultisizeImageReference
   * @class
   * @param small {module:model/DirectoryImageReference} 
   * @param large {module:model/DirectoryImageReference} 
   */
  var exports = function(small, large) {
    var _this = this;

    _this['small'] = small;
    _this['large'] = large;
  };

  /**
   * Constructs a <code>DirectoryMultisizeImageReference</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DirectoryMultisizeImageReference} obj Optional instance to populate.
   * @return {module:model/DirectoryMultisizeImageReference} The populated <code>DirectoryMultisizeImageReference</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('small')) {
        obj['small'] = DirectoryImageReference.constructFromObject(data['small']);
      }
      if (data.hasOwnProperty('large')) {
        obj['large'] = DirectoryImageReference.constructFromObject(data['large']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/DirectoryImageReference} small
   */
  exports.prototype['small'] = undefined;
  /**
   * @member {module:model/DirectoryImageReference} large
   */
  exports.prototype['large'] = undefined;



  return exports;
}));


