/**
 * Swiss Corporate API
 * This is the release candidate version of the \"Swiss Corporate API\" specification. 
 *
 * OpenAPI spec version: 1.0.0.2-SNAPSHOT
 * Contact: swisscorpapi@six-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HealthCheckResponseReceivedHeaders'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./HealthCheckResponseReceivedHeaders'));
  } else {
    // Browser globals (root is window)
    if (!root.SwissCorporateApi) {
      root.SwissCorporateApi = {};
    }
    root.SwissCorporateApi.HealthCheckResponse = factory(root.SwissCorporateApi.ApiClient, root.SwissCorporateApi.HealthCheckResponseReceivedHeaders);
  }
}(this, function(ApiClient, HealthCheckResponseReceivedHeaders) {
  'use strict';




  /**
   * The HealthCheckResponse model module.
   * @module model/HealthCheckResponse
   * @version 1.0.0.2-SNAPSHOT
   */

  /**
   * Constructs a new <code>HealthCheckResponse</code>.
   * @alias module:model/HealthCheckResponse
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>HealthCheckResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HealthCheckResponse} obj Optional instance to populate.
   * @return {module:model/HealthCheckResponse} The populated <code>HealthCheckResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('requestDateTime')) {
        obj['requestDateTime'] = ApiClient.convertToType(data['requestDateTime'], 'Date');
      }
      if (data.hasOwnProperty('receivedHeaders')) {
        obj['receivedHeaders'] = ApiClient.convertToType(data['receivedHeaders'], [HealthCheckResponseReceivedHeaders]);
      }
      if (data.hasOwnProperty('receivedPayload')) {
        obj['receivedPayload'] = ApiClient.convertToType(data['receivedPayload'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Date} requestDateTime
   */
  exports.prototype['requestDateTime'] = undefined;
  /**
   * @member {Array.<module:model/HealthCheckResponseReceivedHeaders>} receivedHeaders
   */
  exports.prototype['receivedHeaders'] = undefined;
  /**
   * @member {String} receivedPayload
   */
  exports.prototype['receivedPayload'] = undefined;



  return exports;
}));


