/**
 * Swiss Corporate API
 * This is the release candidate version of the \"Swiss Corporate API\" specification. 
 *
 * OpenAPI spec version: 1.0.0.2-SNAPSHOT
 * Contact: swisscorpapi@six-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwissCorporateApi) {
      root.SwissCorporateApi = {};
    }
    root.SwissCorporateApi.HealthCheckResponseReceivedHeaders = factory(root.SwissCorporateApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The HealthCheckResponseReceivedHeaders model module.
   * @module model/HealthCheckResponseReceivedHeaders
   * @version 1.0.0.2-SNAPSHOT
   */

  /**
   * Constructs a new <code>HealthCheckResponseReceivedHeaders</code>.
   * @alias module:model/HealthCheckResponseReceivedHeaders
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>HealthCheckResponseReceivedHeaders</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HealthCheckResponseReceivedHeaders} obj Optional instance to populate.
   * @return {module:model/HealthCheckResponseReceivedHeaders} The populated <code>HealthCheckResponseReceivedHeaders</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('headerName')) {
        obj['headerName'] = ApiClient.convertToType(data['headerName'], 'String');
      }
      if (data.hasOwnProperty('headerValue')) {
        obj['headerValue'] = ApiClient.convertToType(data['headerValue'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} headerName
   */
  exports.prototype['headerName'] = undefined;
  /**
   * As received
   * @member {String} headerValue
   */
  exports.prototype['headerValue'] = undefined;



  return exports;
}));


