/**
 * Swiss Corporate API
 * This is the release candidate version of the \"Swiss Corporate API\" specification. 
 *
 * OpenAPI spec version: 1.0.0.2-SNAPSHOT
 * Contact: swisscorpapi@six-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwissCorporateApi) {
      root.SwissCorporateApi = {};
    }
    root.SwissCorporateApi.PaymentInstructionItemStatus = factory(root.SwissCorporateApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PaymentInstructionItemStatus model module.
   * @module model/PaymentInstructionItemStatus
   * @version 1.0.0.2-SNAPSHOT
   */

  /**
   * Constructs a new <code>PaymentInstructionItemStatus</code>.
   * @alias module:model/PaymentInstructionItemStatus
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>PaymentInstructionItemStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaymentInstructionItemStatus} obj Optional instance to populate.
   * @return {module:model/PaymentInstructionItemStatus} The populated <code>PaymentInstructionItemStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('instructionId')) {
        obj['instructionId'] = ApiClient.convertToType(data['instructionId'], 'String');
      }
      if (data.hasOwnProperty('statusCode')) {
        obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'String');
      }
      if (data.hasOwnProperty('reasonCode')) {
        obj['reasonCode'] = ApiClient.convertToType(data['reasonCode'], 'String');
      }
      if (data.hasOwnProperty('reasonInformation')) {
        obj['reasonInformation'] = ApiClient.convertToType(data['reasonInformation'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} instructionId
   */
  exports.prototype['instructionId'] = undefined;
  /**
   * @member {module:model/PaymentInstructionItemStatus.StatusCodeEnum} statusCode
   */
  exports.prototype['statusCode'] = undefined;
  /**
   * @member {String} reasonCode
   */
  exports.prototype['reasonCode'] = undefined;
  /**
   * @member {String} reasonInformation
   */
  exports.prototype['reasonInformation'] = undefined;


  /**
   * Allowed values for the <code>statusCode</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusCodeEnum = {
    /**
     * value: "ACCP"
     * @const
     */
    "ACCP": "ACCP",
    /**
     * value: "RJCT"
     * @const
     */
    "RJCT": "RJCT"  };


  return exports;
}));


