/**
 * Swiss Corporate API
 * This is the release candidate version of the \"Swiss Corporate API\" specification. 
 *
 * OpenAPI spec version: 1.0.0.2-SNAPSHOT
 * Contact: swisscorpapi@six-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwissCorporateApi) {
      root.SwissCorporateApi = {};
    }
    root.SwissCorporateApi.PaymentChargeBearerMethod = factory(root.SwissCorporateApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class PaymentChargeBearerMethod.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "DEBT"
     * @const
     */
    "DEBT": "DEBT",
    /**
     * value: "CRED"
     * @const
     */
    "CRED": "CRED",
    /**
     * value: "SHAR"
     * @const
     */
    "SHAR": "SHAR",
    /**
     * value: "SLEV"
     * @const
     */
    "SLEV": "SLEV"  };

  /**
   * Returns a <code>PaymentChargeBearerMethod</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/PaymentChargeBearerMethod} The enum <code>PaymentChargeBearerMethod</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


