/**
 * Swiss Corporate API
 * This is the release candidate version of the \"Swiss Corporate API\" specification. 
 *
 * OpenAPI spec version: 1.0.0.2-SNAPSHOT
 * Contact: swisscorpapi@six-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PaymentInstructionItemStatus'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PaymentInstructionItemStatus'));
  } else {
    // Browser globals (root is window)
    if (!root.SwissCorporateApi) {
      root.SwissCorporateApi = {};
    }
    root.SwissCorporateApi.PaymentSubmissionStatus = factory(root.SwissCorporateApi.ApiClient, root.SwissCorporateApi.PaymentInstructionItemStatus);
  }
}(this, function(ApiClient, PaymentInstructionItemStatus) {
  'use strict';




  /**
   * The PaymentSubmissionStatus model module.
   * @module model/PaymentSubmissionStatus
   * @version 1.0.0.2-SNAPSHOT
   */

  /**
   * Constructs a new <code>PaymentSubmissionStatus</code>.
   * @alias module:model/PaymentSubmissionStatus
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>PaymentSubmissionStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaymentSubmissionStatus} obj Optional instance to populate.
   * @return {module:model/PaymentSubmissionStatus} The populated <code>PaymentSubmissionStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('messageId')) {
        obj['messageId'] = ApiClient.convertToType(data['messageId'], 'String');
      }
      if (data.hasOwnProperty('statusCode')) {
        obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'String');
      }
      if (data.hasOwnProperty('transactions')) {
        obj['transactions'] = ApiClient.convertToType(data['transactions'], [PaymentInstructionItemStatus]);
      }
    }
    return obj;
  }

  /**
   * @member {String} messageId
   */
  exports.prototype['messageId'] = undefined;
  /**
   * @member {module:model/PaymentSubmissionStatus.StatusCodeEnum} statusCode
   */
  exports.prototype['statusCode'] = undefined;
  /**
   * @member {Array.<module:model/PaymentInstructionItemStatus>} transactions
   */
  exports.prototype['transactions'] = undefined;


  /**
   * Allowed values for the <code>statusCode</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusCodeEnum = {
    /**
     * value: "ACCP"
     * @const
     */
    "ACCP": "ACCP",
    /**
     * value: "RJCT"
     * @const
     */
    "RJCT": "RJCT",
    /**
     * value: "PART"
     * @const
     */
    "PART": "PART"  };


  return exports;
}));


