# coding: utf-8

"""
    Swiss Corporate API

    This is the release candidate version of the \"Swiss Corporate API\" specification.   # noqa: E501

    OpenAPI spec version: 1.0.0.2-SNAPSHOT
    Contact: swisscorpapi@six-group.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class OauthApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def oauth_token(self, grant_type, client_id, x_cor_api_target_id, x_cor_api_client_id, x_correlation_id, user_agent, x_psu_ip_address, x_psu_user_agent, **kwargs):  # noqa: E501
        """Get the OAuth access and refresh token  # noqa: E501

        Returns the OAuth access and refresh token for the specified client and target   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.oauth_token(grant_type, client_id, x_cor_api_target_id, x_cor_api_client_id, x_correlation_id, user_agent, x_psu_ip_address, x_psu_user_agent, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str grant_type: either authorization_code or refresh_token (required)
        :param str client_id: client id (required)
        :param str x_cor_api_target_id: ID that identifies the provider (e.g., a financial institution). (SCOPE: SIX) (required)
        :param str x_cor_api_client_id: ID of the client forwarded to the provider. (SCOPE: FI) (required)
        :param str x_correlation_id: Unique ID (defined by the caller) which will be reflected back in the response. (required)
        :param str user_agent: Name and version of the of the Client software (required)
        :param str x_psu_ip_address: IP address of the user initiating the operation (required)
        :param str x_psu_user_agent: User agent of the user initiating the operation (required)
        :param str code: authorization code if applicable
        :param str refresh_token: refresh token if applicable
        :param str redirect_uri: original redirect uri if applicable
        :return: OauthTokenResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.oauth_token_with_http_info(grant_type, client_id, x_cor_api_target_id, x_cor_api_client_id, x_correlation_id, user_agent, x_psu_ip_address, x_psu_user_agent, **kwargs)  # noqa: E501
        else:
            (data) = self.oauth_token_with_http_info(grant_type, client_id, x_cor_api_target_id, x_cor_api_client_id, x_correlation_id, user_agent, x_psu_ip_address, x_psu_user_agent, **kwargs)  # noqa: E501
            return data

    def oauth_token_with_http_info(self, grant_type, client_id, x_cor_api_target_id, x_cor_api_client_id, x_correlation_id, user_agent, x_psu_ip_address, x_psu_user_agent, **kwargs):  # noqa: E501
        """Get the OAuth access and refresh token  # noqa: E501

        Returns the OAuth access and refresh token for the specified client and target   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.oauth_token_with_http_info(grant_type, client_id, x_cor_api_target_id, x_cor_api_client_id, x_correlation_id, user_agent, x_psu_ip_address, x_psu_user_agent, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str grant_type: either authorization_code or refresh_token (required)
        :param str client_id: client id (required)
        :param str x_cor_api_target_id: ID that identifies the provider (e.g., a financial institution). (SCOPE: SIX) (required)
        :param str x_cor_api_client_id: ID of the client forwarded to the provider. (SCOPE: FI) (required)
        :param str x_correlation_id: Unique ID (defined by the caller) which will be reflected back in the response. (required)
        :param str user_agent: Name and version of the of the Client software (required)
        :param str x_psu_ip_address: IP address of the user initiating the operation (required)
        :param str x_psu_user_agent: User agent of the user initiating the operation (required)
        :param str code: authorization code if applicable
        :param str refresh_token: refresh token if applicable
        :param str redirect_uri: original redirect uri if applicable
        :return: OauthTokenResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['grant_type', 'client_id', 'x_cor_api_target_id', 'x_cor_api_client_id', 'x_correlation_id', 'user_agent', 'x_psu_ip_address', 'x_psu_user_agent', 'code', 'refresh_token', 'redirect_uri']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method oauth_token" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'grant_type' is set
        if ('grant_type' not in params or
                params['grant_type'] is None):
            raise ValueError("Missing the required parameter `grant_type` when calling `oauth_token`")  # noqa: E501
        # verify the required parameter 'client_id' is set
        if ('client_id' not in params or
                params['client_id'] is None):
            raise ValueError("Missing the required parameter `client_id` when calling `oauth_token`")  # noqa: E501
        # verify the required parameter 'x_cor_api_target_id' is set
        if ('x_cor_api_target_id' not in params or
                params['x_cor_api_target_id'] is None):
            raise ValueError("Missing the required parameter `x_cor_api_target_id` when calling `oauth_token`")  # noqa: E501
        # verify the required parameter 'x_cor_api_client_id' is set
        if ('x_cor_api_client_id' not in params or
                params['x_cor_api_client_id'] is None):
            raise ValueError("Missing the required parameter `x_cor_api_client_id` when calling `oauth_token`")  # noqa: E501
        # verify the required parameter 'x_correlation_id' is set
        if ('x_correlation_id' not in params or
                params['x_correlation_id'] is None):
            raise ValueError("Missing the required parameter `x_correlation_id` when calling `oauth_token`")  # noqa: E501
        # verify the required parameter 'user_agent' is set
        if ('user_agent' not in params or
                params['user_agent'] is None):
            raise ValueError("Missing the required parameter `user_agent` when calling `oauth_token`")  # noqa: E501
        # verify the required parameter 'x_psu_ip_address' is set
        if ('x_psu_ip_address' not in params or
                params['x_psu_ip_address'] is None):
            raise ValueError("Missing the required parameter `x_psu_ip_address` when calling `oauth_token`")  # noqa: E501
        # verify the required parameter 'x_psu_user_agent' is set
        if ('x_psu_user_agent' not in params or
                params['x_psu_user_agent'] is None):
            raise ValueError("Missing the required parameter `x_psu_user_agent` when calling `oauth_token`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'x_cor_api_target_id' in params:
            header_params['X-CorAPI-Target-ID'] = params['x_cor_api_target_id']  # noqa: E501
        if 'x_cor_api_client_id' in params:
            header_params['X-CorAPI-Client-ID'] = params['x_cor_api_client_id']  # noqa: E501
        if 'x_correlation_id' in params:
            header_params['X-Correlation-ID'] = params['x_correlation_id']  # noqa: E501
        if 'user_agent' in params:
            header_params['User-Agent'] = params['user_agent']  # noqa: E501
        if 'x_psu_ip_address' in params:
            header_params['X-PSU-IP-Address'] = params['x_psu_ip_address']  # noqa: E501
        if 'x_psu_user_agent' in params:
            header_params['X-PSU-User-Agent'] = params['x_psu_user_agent']  # noqa: E501

        form_params = []
        local_var_files = {}
        if 'grant_type' in params:
            form_params.append(('grant_type', params['grant_type']))  # noqa: E501
        if 'code' in params:
            form_params.append(('code', params['code']))  # noqa: E501
        if 'refresh_token' in params:
            form_params.append(('refresh_token', params['refresh_token']))  # noqa: E501
        if 'redirect_uri' in params:
            form_params.append(('redirect_uri', params['redirect_uri']))  # noqa: E501
        if 'client_id' in params:
            form_params.append(('client_id', params['client_id']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/oauth/token', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='OauthTokenResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
