/**
 * Swiss Corporate API
 * This is the release candidate version of the \"Swiss Corporate API\" specification. 
 *
 * OpenAPI spec version: 1.0.0.2-SNAPSHOT
 * Contact: swisscorpapi@six-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccountBalanceItem', 'model/AccountItem', 'model/AccountTransactionReport', 'model/CommonErrorResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AccountBalanceItem'), require('../model/AccountItem'), require('../model/AccountTransactionReport'), require('../model/CommonErrorResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.SwissCorporateApi) {
      root.SwissCorporateApi = {};
    }
    root.SwissCorporateApi.AccountsApi = factory(root.SwissCorporateApi.ApiClient, root.SwissCorporateApi.AccountBalanceItem, root.SwissCorporateApi.AccountItem, root.SwissCorporateApi.AccountTransactionReport, root.SwissCorporateApi.CommonErrorResponse);
  }
}(this, function(ApiClient, AccountBalanceItem, AccountItem, AccountTransactionReport, CommonErrorResponse) {
  'use strict';

  /**
   * Accounts service.
   * @module api/AccountsApi
   * @version 1.0.0.2-SNAPSHOT
   */

  /**
   * Constructs a new AccountsApi. 
   * @alias module:api/AccountsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the requestAccountBalance operation.
     * @callback module:api/AccountsApi~requestAccountBalanceCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AccountBalanceItem} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve account balance information
     * Retrieve account balance information. * Returns the intraday booked balance (ITBD), if called without a date. * Returns the intraday booked balance (ITBD), if called for the current date. * Returns the closing booked balance (CLBD), if called for a past date.
     * @param {String} authorization Bearer followed by a base64 encoded OAuth access token
     * @param {String} accountId id of account
     * @param {String} xCorAPITargetID ID that identifies the provider (e.g., a financial institution). (SCOPE: SIX)
     * @param {String} xCorAPIClientID ID of the client forwarded to the provider. (SCOPE: FI)
     * @param {String} xCorrelationID Unique ID (defined by the caller) which will be reflected back in the response.
     * @param {String} userAgent Name and version of the of the Client software
     * @param {Object} opts Optional parameters
     * @param {Date} opts._date The date to query, formatted as yyyy-mm-dd. (default to the current date)
     * @param {module:api/AccountsApi~requestAccountBalanceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AccountBalanceItem}
     */
    this.requestAccountBalance = function(authorization, accountId, xCorAPITargetID, xCorAPIClientID, xCorrelationID, userAgent, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling requestAccountBalance");
      }

      // verify the required parameter 'accountId' is set
      if (accountId === undefined || accountId === null) {
        throw new Error("Missing the required parameter 'accountId' when calling requestAccountBalance");
      }

      // verify the required parameter 'xCorAPITargetID' is set
      if (xCorAPITargetID === undefined || xCorAPITargetID === null) {
        throw new Error("Missing the required parameter 'xCorAPITargetID' when calling requestAccountBalance");
      }

      // verify the required parameter 'xCorAPIClientID' is set
      if (xCorAPIClientID === undefined || xCorAPIClientID === null) {
        throw new Error("Missing the required parameter 'xCorAPIClientID' when calling requestAccountBalance");
      }

      // verify the required parameter 'xCorrelationID' is set
      if (xCorrelationID === undefined || xCorrelationID === null) {
        throw new Error("Missing the required parameter 'xCorrelationID' when calling requestAccountBalance");
      }

      // verify the required parameter 'userAgent' is set
      if (userAgent === undefined || userAgent === null) {
        throw new Error("Missing the required parameter 'userAgent' when calling requestAccountBalance");
      }


      var pathParams = {
        'accountId': accountId
      };
      var queryParams = {
        'date': opts['_date'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization,
        'X-CorAPI-Target-ID': xCorAPITargetID,
        'X-CorAPI-Client-ID': xCorAPIClientID,
        'X-Correlation-ID': xCorrelationID,
        'User-Agent': userAgent
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = AccountBalanceItem;

      return this.apiClient.callApi(
        '/accounts/{accountId}/balance', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the requestAccountDetails operation.
     * @callback module:api/AccountsApi~requestAccountDetailsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AccountItem} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve information about a single specific account
     * @param {String} authorization Bearer followed by a base64 encoded OAuth access token
     * @param {String} accountId id of account
     * @param {String} xCorAPITargetID ID that identifies the provider (e.g., a financial institution). (SCOPE: SIX)
     * @param {String} xCorAPIClientID ID of the client forwarded to the provider. (SCOPE: FI)
     * @param {String} xCorrelationID Unique ID (defined by the caller) which will be reflected back in the response.
     * @param {String} userAgent Name and version of the of the Client software
     * @param {module:api/AccountsApi~requestAccountDetailsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AccountItem}
     */
    this.requestAccountDetails = function(authorization, accountId, xCorAPITargetID, xCorAPIClientID, xCorrelationID, userAgent, callback) {
      var postBody = null;

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling requestAccountDetails");
      }

      // verify the required parameter 'accountId' is set
      if (accountId === undefined || accountId === null) {
        throw new Error("Missing the required parameter 'accountId' when calling requestAccountDetails");
      }

      // verify the required parameter 'xCorAPITargetID' is set
      if (xCorAPITargetID === undefined || xCorAPITargetID === null) {
        throw new Error("Missing the required parameter 'xCorAPITargetID' when calling requestAccountDetails");
      }

      // verify the required parameter 'xCorAPIClientID' is set
      if (xCorAPIClientID === undefined || xCorAPIClientID === null) {
        throw new Error("Missing the required parameter 'xCorAPIClientID' when calling requestAccountDetails");
      }

      // verify the required parameter 'xCorrelationID' is set
      if (xCorrelationID === undefined || xCorrelationID === null) {
        throw new Error("Missing the required parameter 'xCorrelationID' when calling requestAccountDetails");
      }

      // verify the required parameter 'userAgent' is set
      if (userAgent === undefined || userAgent === null) {
        throw new Error("Missing the required parameter 'userAgent' when calling requestAccountDetails");
      }


      var pathParams = {
        'accountId': accountId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization,
        'X-CorAPI-Target-ID': xCorAPITargetID,
        'X-CorAPI-Client-ID': xCorAPIClientID,
        'X-Correlation-ID': xCorrelationID,
        'User-Agent': userAgent
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = AccountItem;

      return this.apiClient.callApi(
        '/accounts/{accountId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the requestAccountList operation.
     * @callback module:api/AccountsApi~requestAccountListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AccountItem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve list of authorized accounts
     * @param {String} authorization Bearer followed by a base64 encoded OAuth access token
     * @param {String} xCorAPITargetID ID that identifies the provider (e.g., a financial institution). (SCOPE: SIX)
     * @param {String} xCorAPIClientID ID of the client forwarded to the provider. (SCOPE: FI)
     * @param {String} xCorrelationID Unique ID (defined by the caller) which will be reflected back in the response.
     * @param {String} userAgent Name and version of the of the Client software
     * @param {module:api/AccountsApi~requestAccountListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AccountItem>}
     */
    this.requestAccountList = function(authorization, xCorAPITargetID, xCorAPIClientID, xCorrelationID, userAgent, callback) {
      var postBody = null;

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling requestAccountList");
      }

      // verify the required parameter 'xCorAPITargetID' is set
      if (xCorAPITargetID === undefined || xCorAPITargetID === null) {
        throw new Error("Missing the required parameter 'xCorAPITargetID' when calling requestAccountList");
      }

      // verify the required parameter 'xCorAPIClientID' is set
      if (xCorAPIClientID === undefined || xCorAPIClientID === null) {
        throw new Error("Missing the required parameter 'xCorAPIClientID' when calling requestAccountList");
      }

      // verify the required parameter 'xCorrelationID' is set
      if (xCorrelationID === undefined || xCorrelationID === null) {
        throw new Error("Missing the required parameter 'xCorrelationID' when calling requestAccountList");
      }

      // verify the required parameter 'userAgent' is set
      if (userAgent === undefined || userAgent === null) {
        throw new Error("Missing the required parameter 'userAgent' when calling requestAccountList");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization,
        'X-CorAPI-Target-ID': xCorAPITargetID,
        'X-CorAPI-Client-ID': xCorAPIClientID,
        'X-Correlation-ID': xCorrelationID,
        'User-Agent': userAgent
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [AccountItem];

      return this.apiClient.callApi(
        '/accounts', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the requestAccountTransactions operation.
     * @callback module:api/AccountsApi~requestAccountTransactionsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AccountTransactionReport} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve transactions of a specific account
     * * Returns the transaction list of the current day, if called without a date. * Returns the transaction list for a specific day, if called for a past date. In case the specified day has not yet been finalized, the response will be a 404 error. 
     * @param {String} authorization Bearer followed by a base64 encoded OAuth access token
     * @param {String} accountId id of account
     * @param {String} xCorAPITargetID ID that identifies the provider (e.g., a financial institution). (SCOPE: SIX)
     * @param {String} xCorAPIClientID ID of the client forwarded to the provider. (SCOPE: FI)
     * @param {String} xCorrelationID Unique ID (defined by the caller) which will be reflected back in the response.
     * @param {String} userAgent Name and version of the of the Client software
     * @param {Object} opts Optional parameters
     * @param {Date} opts._date The date to query, formatted as yyyy-mm-dd. (default to the current date)
     * @param {module:api/AccountsApi~requestAccountTransactionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AccountTransactionReport}
     */
    this.requestAccountTransactions = function(authorization, accountId, xCorAPITargetID, xCorAPIClientID, xCorrelationID, userAgent, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling requestAccountTransactions");
      }

      // verify the required parameter 'accountId' is set
      if (accountId === undefined || accountId === null) {
        throw new Error("Missing the required parameter 'accountId' when calling requestAccountTransactions");
      }

      // verify the required parameter 'xCorAPITargetID' is set
      if (xCorAPITargetID === undefined || xCorAPITargetID === null) {
        throw new Error("Missing the required parameter 'xCorAPITargetID' when calling requestAccountTransactions");
      }

      // verify the required parameter 'xCorAPIClientID' is set
      if (xCorAPIClientID === undefined || xCorAPIClientID === null) {
        throw new Error("Missing the required parameter 'xCorAPIClientID' when calling requestAccountTransactions");
      }

      // verify the required parameter 'xCorrelationID' is set
      if (xCorrelationID === undefined || xCorrelationID === null) {
        throw new Error("Missing the required parameter 'xCorrelationID' when calling requestAccountTransactions");
      }

      // verify the required parameter 'userAgent' is set
      if (userAgent === undefined || userAgent === null) {
        throw new Error("Missing the required parameter 'userAgent' when calling requestAccountTransactions");
      }


      var pathParams = {
        'accountId': accountId
      };
      var queryParams = {
        'date': opts['_date'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization,
        'X-CorAPI-Target-ID': xCorAPITargetID,
        'X-CorAPI-Client-ID': xCorAPIClientID,
        'X-Correlation-ID': xCorrelationID,
        'User-Agent': userAgent
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = AccountTransactionReport;

      return this.apiClient.callApi(
        '/accounts/{accountId}/transactions', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
