# coding: utf-8

"""
    Swiss Corporate API

    This is the release candidate version of the \"Swiss Corporate API\" specification.   # noqa: E501

    OpenAPI spec version: 1.0.0.2-SNAPSHOT
    Contact: swisscorpapi@six-group.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.consent_account_item import ConsentAccountItem  # noqa: F401,E501


class ConsentItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'use_case': 'str',
        'accounts': 'list[ConsentAccountItem]'
    }

    attribute_map = {
        'use_case': 'useCase',
        'accounts': 'accounts'
    }

    def __init__(self, use_case=None, accounts=None):  # noqa: E501
        """ConsentItem - a model defined in Swagger"""  # noqa: E501

        self._use_case = None
        self._accounts = None
        self.discriminator = None

        if use_case is not None:
            self.use_case = use_case
        if accounts is not None:
            self.accounts = accounts

    @property
    def use_case(self):
        """Gets the use_case of this ConsentItem.  # noqa: E501


        :return: The use_case of this ConsentItem.  # noqa: E501
        :rtype: str
        """
        return self._use_case

    @use_case.setter
    def use_case(self, use_case):
        """Sets the use_case of this ConsentItem.


        :param use_case: The use_case of this ConsentItem.  # noqa: E501
        :type: str
        """

        self._use_case = use_case

    @property
    def accounts(self):
        """Gets the accounts of this ConsentItem.  # noqa: E501


        :return: The accounts of this ConsentItem.  # noqa: E501
        :rtype: list[ConsentAccountItem]
        """
        return self._accounts

    @accounts.setter
    def accounts(self, accounts):
        """Sets the accounts of this ConsentItem.


        :param accounts: The accounts of this ConsentItem.  # noqa: E501
        :type: list[ConsentAccountItem]
        """

        self._accounts = accounts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConsentItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConsentItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
