# coding: utf-8

"""
    Swiss Corporate API

    This is the release candidate version of the \"Swiss Corporate API\" specification.   # noqa: E501

    OpenAPI spec version: 1.0.0.2-SNAPSHOT
    Contact: swisscorpapi@six-group.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PaymentInstructionItemStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'instruction_id': 'str',
        'status_code': 'str',
        'reason_code': 'str',
        'reason_information': 'str'
    }

    attribute_map = {
        'instruction_id': 'instructionId',
        'status_code': 'statusCode',
        'reason_code': 'reasonCode',
        'reason_information': 'reasonInformation'
    }

    def __init__(self, instruction_id=None, status_code=None, reason_code=None, reason_information=None):  # noqa: E501
        """PaymentInstructionItemStatus - a model defined in Swagger"""  # noqa: E501

        self._instruction_id = None
        self._status_code = None
        self._reason_code = None
        self._reason_information = None
        self.discriminator = None

        if instruction_id is not None:
            self.instruction_id = instruction_id
        if status_code is not None:
            self.status_code = status_code
        if reason_code is not None:
            self.reason_code = reason_code
        if reason_information is not None:
            self.reason_information = reason_information

    @property
    def instruction_id(self):
        """Gets the instruction_id of this PaymentInstructionItemStatus.  # noqa: E501


        :return: The instruction_id of this PaymentInstructionItemStatus.  # noqa: E501
        :rtype: str
        """
        return self._instruction_id

    @instruction_id.setter
    def instruction_id(self, instruction_id):
        """Sets the instruction_id of this PaymentInstructionItemStatus.


        :param instruction_id: The instruction_id of this PaymentInstructionItemStatus.  # noqa: E501
        :type: str
        """

        self._instruction_id = instruction_id

    @property
    def status_code(self):
        """Gets the status_code of this PaymentInstructionItemStatus.  # noqa: E501


        :return: The status_code of this PaymentInstructionItemStatus.  # noqa: E501
        :rtype: str
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code):
        """Sets the status_code of this PaymentInstructionItemStatus.


        :param status_code: The status_code of this PaymentInstructionItemStatus.  # noqa: E501
        :type: str
        """
        allowed_values = ["ACCP", "RJCT"]  # noqa: E501
        if status_code not in allowed_values:
            raise ValueError(
                "Invalid value for `status_code` ({0}), must be one of {1}"  # noqa: E501
                .format(status_code, allowed_values)
            )

        self._status_code = status_code

    @property
    def reason_code(self):
        """Gets the reason_code of this PaymentInstructionItemStatus.  # noqa: E501


        :return: The reason_code of this PaymentInstructionItemStatus.  # noqa: E501
        :rtype: str
        """
        return self._reason_code

    @reason_code.setter
    def reason_code(self, reason_code):
        """Sets the reason_code of this PaymentInstructionItemStatus.


        :param reason_code: The reason_code of this PaymentInstructionItemStatus.  # noqa: E501
        :type: str
        """

        self._reason_code = reason_code

    @property
    def reason_information(self):
        """Gets the reason_information of this PaymentInstructionItemStatus.  # noqa: E501


        :return: The reason_information of this PaymentInstructionItemStatus.  # noqa: E501
        :rtype: str
        """
        return self._reason_information

    @reason_information.setter
    def reason_information(self, reason_information):
        """Sets the reason_information of this PaymentInstructionItemStatus.


        :param reason_information: The reason_information of this PaymentInstructionItemStatus.  # noqa: E501
        :type: str
        """

        self._reason_information = reason_information

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PaymentInstructionItemStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaymentInstructionItemStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
