# coding: utf-8

"""
    Swiss Corporate API

    This is the release candidate version of the \"Swiss Corporate API\" specification.   # noqa: E501

    OpenAPI spec version: 1.0.0.2-SNAPSHOT
    Contact: swisscorpapi@six-group.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.payment_charge_bearer_method import PaymentChargeBearerMethod  # noqa: F401,E501
from swagger_client.models.payment_creditor import PaymentCreditor  # noqa: F401,E501
from swagger_client.models.payment_creditor_agent import PaymentCreditorAgent  # noqa: F401,E501
from swagger_client.models.payment_other_account import PaymentOtherAccount  # noqa: F401,E501
from swagger_client.models.payment_other_remittance_reference import PaymentOtherRemittanceReference  # noqa: F401,E501


class PaymentOtherDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'creditor_account': 'PaymentOtherAccount',
        'creditor_agent': 'PaymentCreditorAgent',
        'creditor': 'PaymentCreditor',
        'charge_bearer': 'PaymentChargeBearerMethod',
        'remittance_reference': 'PaymentOtherRemittanceReference'
    }

    attribute_map = {
        'creditor_account': 'creditorAccount',
        'creditor_agent': 'creditorAgent',
        'creditor': 'creditor',
        'charge_bearer': 'chargeBearer',
        'remittance_reference': 'remittanceReference'
    }

    def __init__(self, creditor_account=None, creditor_agent=None, creditor=None, charge_bearer=None, remittance_reference=None):  # noqa: E501
        """PaymentOtherDetail - a model defined in Swagger"""  # noqa: E501

        self._creditor_account = None
        self._creditor_agent = None
        self._creditor = None
        self._charge_bearer = None
        self._remittance_reference = None
        self.discriminator = None

        if creditor_account is not None:
            self.creditor_account = creditor_account
        if creditor_agent is not None:
            self.creditor_agent = creditor_agent
        if creditor is not None:
            self.creditor = creditor
        if charge_bearer is not None:
            self.charge_bearer = charge_bearer
        if remittance_reference is not None:
            self.remittance_reference = remittance_reference

    @property
    def creditor_account(self):
        """Gets the creditor_account of this PaymentOtherDetail.  # noqa: E501


        :return: The creditor_account of this PaymentOtherDetail.  # noqa: E501
        :rtype: PaymentOtherAccount
        """
        return self._creditor_account

    @creditor_account.setter
    def creditor_account(self, creditor_account):
        """Sets the creditor_account of this PaymentOtherDetail.


        :param creditor_account: The creditor_account of this PaymentOtherDetail.  # noqa: E501
        :type: PaymentOtherAccount
        """

        self._creditor_account = creditor_account

    @property
    def creditor_agent(self):
        """Gets the creditor_agent of this PaymentOtherDetail.  # noqa: E501


        :return: The creditor_agent of this PaymentOtherDetail.  # noqa: E501
        :rtype: PaymentCreditorAgent
        """
        return self._creditor_agent

    @creditor_agent.setter
    def creditor_agent(self, creditor_agent):
        """Sets the creditor_agent of this PaymentOtherDetail.


        :param creditor_agent: The creditor_agent of this PaymentOtherDetail.  # noqa: E501
        :type: PaymentCreditorAgent
        """

        self._creditor_agent = creditor_agent

    @property
    def creditor(self):
        """Gets the creditor of this PaymentOtherDetail.  # noqa: E501


        :return: The creditor of this PaymentOtherDetail.  # noqa: E501
        :rtype: PaymentCreditor
        """
        return self._creditor

    @creditor.setter
    def creditor(self, creditor):
        """Sets the creditor of this PaymentOtherDetail.


        :param creditor: The creditor of this PaymentOtherDetail.  # noqa: E501
        :type: PaymentCreditor
        """

        self._creditor = creditor

    @property
    def charge_bearer(self):
        """Gets the charge_bearer of this PaymentOtherDetail.  # noqa: E501


        :return: The charge_bearer of this PaymentOtherDetail.  # noqa: E501
        :rtype: PaymentChargeBearerMethod
        """
        return self._charge_bearer

    @charge_bearer.setter
    def charge_bearer(self, charge_bearer):
        """Sets the charge_bearer of this PaymentOtherDetail.


        :param charge_bearer: The charge_bearer of this PaymentOtherDetail.  # noqa: E501
        :type: PaymentChargeBearerMethod
        """

        self._charge_bearer = charge_bearer

    @property
    def remittance_reference(self):
        """Gets the remittance_reference of this PaymentOtherDetail.  # noqa: E501


        :return: The remittance_reference of this PaymentOtherDetail.  # noqa: E501
        :rtype: PaymentOtherRemittanceReference
        """
        return self._remittance_reference

    @remittance_reference.setter
    def remittance_reference(self, remittance_reference):
        """Sets the remittance_reference of this PaymentOtherDetail.


        :param remittance_reference: The remittance_reference of this PaymentOtherDetail.  # noqa: E501
        :type: PaymentOtherRemittanceReference
        """

        self._remittance_reference = remittance_reference

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PaymentOtherDetail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaymentOtherDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
