/**
 * Swiss Corporate API
 * This is the release candidate version of the \"Swiss Corporate API\" specification. 
 *
 * OpenAPI spec version: 1.0.0.2-SNAPSHOT
 * Contact: swisscorpapi@six-group.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwissCorporateApi);
  }
}(this, function(expect, SwissCorporateApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwissCorporateApi.AccountTransactionItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AccountTransactionItem', function() {
    it('should create an instance of AccountTransactionItem', function() {
      // uncomment below and update the code to test AccountTransactionItem
      //var instance = new SwissCorporateApi.AccountTransactionItem();
      //expect(instance).to.be.a(SwissCorporateApi.AccountTransactionItem);
    });

    it('should have the property transactionId (base name: "transactionId")', function() {
      // uncomment below and update the code to test the property transactionId
      //var instance = new SwissCorporateApi.AccountTransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property transactionType (base name: "transactionType")', function() {
      // uncomment below and update the code to test the property transactionType
      //var instance = new SwissCorporateApi.AccountTransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property endToEndId (base name: "endToEndId")', function() {
      // uncomment below and update the code to test the property endToEndId
      //var instance = new SwissCorporateApi.AccountTransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property bankTransactionCode (base name: "bankTransactionCode")', function() {
      // uncomment below and update the code to test the property bankTransactionCode
      //var instance = new SwissCorporateApi.AccountTransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new SwissCorporateApi.AccountTransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property instructedAmount (base name: "instructedAmount")', function() {
      // uncomment below and update the code to test the property instructedAmount
      //var instance = new SwissCorporateApi.AccountTransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property totalChargesAmount (base name: "totalChargesAmount")', function() {
      // uncomment below and update the code to test the property totalChargesAmount
      //var instance = new SwissCorporateApi.AccountTransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property counterparty (base name: "counterparty")', function() {
      // uncomment below and update the code to test the property counterparty
      //var instance = new SwissCorporateApi.AccountTransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property remittanceInformation (base name: "remittanceInformation")', function() {
      // uncomment below and update the code to test the property remittanceInformation
      //var instance = new SwissCorporateApi.AccountTransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property remittanceReference (base name: "remittanceReference")', function() {
      // uncomment below and update the code to test the property remittanceReference
      //var instance = new SwissCorporateApi.AccountTransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property additionalTransactionInformation (base name: "additionalTransactionInformation")', function() {
      // uncomment below and update the code to test the property additionalTransactionInformation
      //var instance = new SwissCorporateApi.AccountTransactionItem();
      //expect(instance).to.be();
    });

  });

}));
