# coding: utf-8

"""
    Swiss Corporate API

    This is the release candidate version of the \"Swiss Corporate API\" specification.   # noqa: E501

    OpenAPI spec version: 1.0.0.2-SNAPSHOT
    Contact: swisscorpapi@six-group.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.accounts_api import AccountsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.accounts_api.AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_request_account_balance(self):
        """Test case for request_account_balance

        Retrieve account balance information  # noqa: E501
        """
        pass

    def test_request_account_details(self):
        """Test case for request_account_details

        Retrieve information about a single specific account  # noqa: E501
        """
        pass

    def test_request_account_list(self):
        """Test case for request_account_list

        Retrieve list of authorized accounts  # noqa: E501
        """
        pass

    def test_request_account_transactions(self):
        """Test case for request_account_transactions

        Retrieve transactions of a specific account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
