# coding: utf-8

"""
    Swiss Corporate API

    This is the release candidate version of the \"Swiss Corporate API\" specification.   # noqa: E501

    OpenAPI spec version: 1.0.0.2-SNAPSHOT
    Contact: swisscorpapi@six-group.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.iso20022_report_reference import Iso20022ReportReference  # noqa: E501
from swagger_client.rest import ApiException


class TestIso20022ReportReference(unittest.TestCase):
    """Iso20022ReportReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIso20022ReportReference(self):
        """Test Iso20022ReportReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.iso20022_report_reference.Iso20022ReportReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
