# coding: utf-8

"""
    Swiss Corporate API

    This is the release candidate version of the \"Swiss Corporate API\" specification.   # noqa: E501

    OpenAPI spec version: 1.0.0.2-SNAPSHOT
    Contact: swisscorpapi@six-group.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.common_structured_or_unstructured_address import CommonStructuredOrUnstructuredAddress  # noqa: E501
from swagger_client.rest import ApiException


class TestCommonStructuredOrUnstructuredAddress(unittest.TestCase):
    """CommonStructuredOrUnstructuredAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonStructuredOrUnstructuredAddress(self):
        """Test CommonStructuredOrUnstructuredAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.common_structured_or_unstructured_address.CommonStructuredOrUnstructuredAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
