# coding: utf-8

"""
    Swiss Corporate API

    This is the release candidate version of the \"Swiss Corporate API\" specification.   # noqa: E501

    OpenAPI spec version: 1.0.0.2-SNAPSHOT
    Contact: swisscorpapi@six-group.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.account_transaction_counterparty_agent import AccountTransactionCounterpartyAgent  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountTransactionCounterpartyAgent(unittest.TestCase):
    """AccountTransactionCounterpartyAgent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountTransactionCounterpartyAgent(self):
        """Test AccountTransactionCounterpartyAgent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.account_transaction_counterparty_agent.AccountTransactionCounterpartyAgent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
