# coding: utf-8

"""
    Swiss Corporate API

    This is the release candidate version of the \"Swiss Corporate API\" specification.   # noqa: E501

    OpenAPI spec version: 1.0.0.2-SNAPSHOT
    Contact: swisscorpapi@six-group.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.directory_api import DirectoryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDirectoryApi(unittest.TestCase):
    """DirectoryApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.directory_api.DirectoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_client_detail(self):
        """Test case for retrieve_client_detail

        Retrieve the information for a registered client (e.g. third party provider)  # noqa: E501
        """
        pass

    def test_retrieve_clients(self):
        """Test case for retrieve_clients

        Retrieve a list of all registered clients (e.g., third party providers)  # noqa: E501
        """
        pass

    def test_retrieve_provider_detail(self):
        """Test case for retrieve_provider_detail

        Retrieve the informatoin for a registered provider (e.g., financial institutions)  # noqa: E501
        """
        pass

    def test_retrieve_providers(self):
        """Test case for retrieve_providers

        Retrieve a list of all registered providers (e.g., financial institutions)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
