# coding: utf-8

"""
    Swiss Corporate API

    This is the release candidate version of the \"Swiss Corporate API\" specification.   # noqa: E501

    OpenAPI spec version: 1.0.0.2-SNAPSHOT
    Contact: swisscorpapi@six-group.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.diagnostics_api import DiagnosticsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDiagnosticsApi(unittest.TestCase):
    """DiagnosticsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.diagnostics_api.DiagnosticsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_health_check_get(self):
        """Test case for health_check_get

        Returns all specified request headers and additional diagnostic information  # noqa: E501
        """
        pass

    def test_health_check_post(self):
        """Test case for health_check_post

        Returns all specified request headers, the request body and additional diagnostic information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
