# coding: utf-8

"""
    Swiss Corporate API

    This is the release candidate version of the \"Swiss Corporate API\" specification.   # noqa: E501

    OpenAPI spec version: 1.0.0.2-SNAPSHOT
    Contact: swisscorpapi@six-group.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.consents_api import ConsentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestConsentsApi(unittest.TestCase):
    """ConsentsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.consents_api.ConsentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_consents(self):
        """Test case for retrieve_consents

        Retrieve a list of consents  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
